create table drone (id bigint generated always as identity primary key not null, droneid varchar(50) not null, autonomy int default 100, positionx int default 0, positiony int default 0);

create table store (id bigint generated by default as identity (start with 1) primary key, storeid varchar(50) not null unique, positionx int default 0, positiony int default 0);
create table product (id bigint generated by default as identity (start with 1) primary key, productid varchar(50) not null, productname varchar(50), quantity int default 0);

create table store_products (store_id bigint not null, products_id bigint not null,
    primary key (store_id, products_id), foreign key (store_id) references store,  foreign key (products_id) references product);

create table customer (id bigint primary key not null, customerid varchar(50) not null unique, positionx int default 0, positiony int default 0);

create table orders (id bigint primary key not null, orderid varchar(50) not null unique);

create table orderedproduct (id bigint generated always as identity primary key not null,
  order_id bigint not null, foreign key (order_id) references orders,
  customer_id bigint not null, foreign key (customer_id) references customer,
  productid varchar(50) not null,
  quantity bigint not null);